### ISSUE TITLE
Bug in docker/php/Dockerfile

### ISSUE THREAD

**Issue by glazilla** [SimonDevelop/slim-sim#1]
Line 30 : 
--           
--        libzzip-dev
++      libzip-dev

**Comment by SimonDevelop** [comment]
Je l'avais vu mais je n'ai pas eu le temps encore de commiter le correctif :smile:
[Release 1.0.3](https://github.com/SimonDevelop/slim-sim/releases/tag/1.0.3)

**Comment by glazilla** [comment]
Bonsoir Simon.

Je pense que le fait d'avoir laissé une trace pour le correctif peut aider
les utilisateurs.
Trois questions pour vous :

- allez vous continuer ce projet que je trouve très réussi ?
- le porter sur slim 4 ?
- dans votre précédent projet, vous aviez un dossier doc avec les
principales commandes, ce qui était bien utile. Envisagez-vous de
l'intégrer ?

Merci pour ce travail..

Cordialement,

Sylvain

Le jeu. 29 août 2019 à 16:17, Simon Micheneau <notifications@github.com> a
écrit :

**Comment by SimonDevelop** [comment]
Bonsoir,

Oui je vais continuer à maintenir ce projet, la version 4 de slim est prévu il faut que je me trouve un peu plus de temps.
Pour la documentation vous avez le lien sur le README à la fin, il s'agit d'un dépôt dédié à la documentation de ce projet que vous pouvez retrouver là [https://github.com/SimonDevelop/docs-slim-sim](https://github.com/SimonDevelop/docs-slim-sim).

N'hésitez pas à faire un fork et me proposer des `pull requests` qui va dans le sens de l'évolution du projet ;)
