### ISSUE TITLE
Problem with is_current_path ()

### ISSUE THREAD

**Issue by glazilla** [SimonDevelop/slim-sim#2]
When using is_current_path with a named route, I get : 

Type: Error
Message: Call to a member function getBasePath() on string
File: /var/www/slim-sim/vendor/slim/twig-view/src/TwigExtension.php
Line: 93

The problem is in container.php

My suggestion : 
```
-- 42     $basePath = rtrim(str_ireplace('index.php', '', $container['request']->getUri()->getBasePath()), '/');
-- 43    $view->addExtension(new Slim\Views\TwigExtension($container['router'], $basePath));
++ 42 $uri = \Slim\Http\Uri::createFromEnvironment(new \Slim\Http\Environment($_SERVER));
++ 43 $view->addExtension(new Slim\Views\TwigExtension($container['router'], $uri));
```

Regards,
Glazilla

**Comment by SimonDevelop** [comment]
Do you know how to make a Pull Request ? It would be simpler and faster for us.
I do not know if your code works with unit tests, it will also add one for this one.

On my side I have this error with your code and a `dump(is_current_path())`:
```
Type: ArgumentCountError
Message: Too few arguments to function Slim\Views\TwigExtension::isCurrentPath(), 0 passed in /home/simon/Templates/slim-sim/vendor/twig/twig/src/Environment.php(418) : eval()'d code on line 71 and at least 1 expected
File: /home/simon/Templates/slim-sim/vendor/slim/twig-view/src/TwigExtension.php
Line: 91
```

**Comment by glazilla** [comment]
OK, let me know if is ok for you now...

Le lun. 2 sept. 2019 à 09:06, Simon Micheneau <notifications@github.com> a
écrit :

**Comment by SimonDevelop** [comment]
Can you explain to me what is your 'is current_path` for ?
***See my previous error message https://github.com/SimonDevelop/slim-sim/issues/2#issuecomment-527028889***

**Comment by glazilla** [comment]
Yes of course...
In a twig view, it allows you to check if a named route is active in order to, for example, add a specific class... Example : 

>           <li class="nav-item {% if is_current_path('customers') %}active{% endif %}">
>             <a class="nav-link" href="{{path_for('customers')}}"><i class="fa fa-refresh"></i>Customers</a>
>           </li>

**Comment by SimonDevelop** [comment]
Ah ! That's how we use it !
I understand better, thank you for your contribution :smiley:
