### ISSUE TITLE
Migrations not written in app/src/Migrations

### ISSUE THREAD

**Issue by glazilla** [SimonDevelop/slim-sim#4]
Hi,

Doctrine is working perfectly but migrations done are never written in the existing folder app/src/Migrations. What should be done to get Migrations written in this folder .
Thanks,
Sylvain

**Comment by SimonDevelop** [comment]
Hi,

I had not updated the migrations.yaml configuration to version 3 of the latter.
Thing made in release 2.1.3, doc link for commands => https://www.doctrine-project.org/projects/doctrine-migrations/en/3.0/reference/generating-migrations.html

**Comment by glazilla** [comment]
Many thanks, it's perfect...

Le mer. 24 mars 2021 à 12:25, Simon Micheneau ***@***.***> a
écrit :
